name: Build and push docker image

on:
  push:
    branches: [ "main" ]
    
  workflow_dispatch:

jobs:
  job01:
    name: Executando job build and push docker images
    runs-on: ubuntu-latest
    steps:
      - name: Step 1
        uses: actions/checkout@v3

      - name: Docker Login
        uses: docker/login-action@v3.0.0
        with:
          username: 'jpmarques2000'
          password: ${{ secrets.SECRET }}

      - name: Build and push Docker images
        uses: docker/build-push-action@v5.1.0
        with:
          context: .
          tags: 'jpmarques2000/containerdockerapi:latest'
          push: true
        
